version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports: 
            - 27017:27017
        volumes:
            - mongodb_data:/data/db
            - ./restaurantes.json:/restaurantes.json
            - ./queries.js:/queries.js
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=rootuser
            - MONGO_INITDB_ROOT_PASSWORD=rootpass
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
            - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
            - ME_CONFIG_MONGODB_SERVER=mongodb
volumes: 
    mongodb_data: {} 
    
networks:
    default: 
        name: mongodb_network